[versions]
adventure = "4.25.0"
junit = "6.0.1"
blossom = "2.2.0"
shadow = "9.3.0"
fabric-loader = "0.18.1"
fabric-api = "0.135.0+1.21.10"
minecraft = "1.21.10"
adventurefabric = "6.7.0"

[libraries.miniplaceholders]
group = "io.github.miniplaceholders"
name = "miniplaceholders-api"
version = "3.1.0"

[libraries.velocity-api]
group = "com.velocitypowered"
name = "velocity-api"
version = "3.4.0-SNAPSHOT"

[libraries.paper-api]
group = "io.papermc.paper"
name = "paper-api"
version = "1.21.8-R0.1-SNAPSHOT"

[libraries.adventure-minimessage]
group = "net.kyori"
name = "adventure-text-minimessage"
version = { ref = "adventure" }

[libraries.adventure-serializer-plain]
group = "net.kyori"
name = "adventure-text-serializer-plain"
version = { ref = "adventure" }

[libraries.snakeyaml]
group = "org.yaml"
name = "snakeyaml"
version = "2.5"

[libraries.junit-jupiter-api]
group = "org.junit.jupiter"
name = "junit-jupiter-api"
version = { ref = "junit" }

[libraries.junit-jupiter-engine]
group = "org.junit.jupiter"
name = "junit-jupiter-engine"
version = { ref = "junit" }

[libraries.fabric-loader]
group = "net.fabricmc"
name = "fabric-loader"
version = { ref = "fabric-loader" }

[libraries.fabric-api]
group = "net.fabricmc.fabric-api"
name = "fabric-api"
version = { ref = "fabric-api" }

[libraries.minecraft]
group = "com.mojang"
name = "minecraft"
version = { ref = "minecraft" }

[libraries.adventure-platform-fabric]
group = "net.kyori"
name = "adventure-platform-fabric"
version = { ref = "adventurefabric" }

[bundles]
minimessage = ["adventure-minimessage", "adventure-serializer-plain"]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runpaper = { id = "xyz.jpenilla.run-paper", version = "3.0.2" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }
